### ISSUE TITLE
SCT可以用于别的跟踪器吗

### ISSUE THREAD

**Issue by Ac2333** [vision4robotics/SCT#1]
SCT可以用于别的跟踪器吗

**Comment by Jay-Ye** [comment]
SCT is designed to be a general enhancer for various trackers, while its benefits for other trackers are not guaranteed. You may need further fine-tuning and retraining.

**Comment by Ac2333** [comment]
那我要如何把SCT添加到我自己的跟踪器上呢？

**Comment by Ac2333** [comment]
So how do I add SCT to my own tracker?

**Comment by Jay-Ye** [comment]
There are several demos in [tracker_set](https://github.com/vision4robotics/SCT/tree/main/tracker_set). For example, the SCT model is loaded [here](https://github.com/vision4robotics/SCT/blob/d130722909be6de82ed14d2dae3b1151de6f29cc/tracker_set/HiFT/tools/test.py#LL64C1-L68C23), and then passed to the ['tracker.init'](https://github.com/vision4robotics/SCT/blob/d130722909be6de82ed14d2dae3b1151de6f29cc/tracker_set/HiFT/tools/test.py#LL88C1-L88C57) function and ['tracker.track'](https://github.com/vision4robotics/SCT/blob/d130722909be6de82ed14d2dae3b1151de6f29cc/tracker_set/HiFT/tools/test.py#LL96C1-L96C58) function. You can dive into these functions for more information.

**Comment by Ac2333** [comment]
Thank you very much！！
