### ISSUE TITLE
Some questions about the DarkTrack2021 dataset

### ISSUE THREAD

**Issue by haaWei** [vision4robotics/SCT#2]
Hi Author, I see that there are 141 test sequences in your test results about DarkTrack2021 section, while there are 110 sequences in DarkTrack2021, I would like to ask why the difference?

**Comment by Jay-Ye** [comment]
Sorry for the inconvenience, the previous files are wrong. I've uploaded the correct version of the test results.

**Comment by haaWei** [comment]
> 抱歉给您带来不便，之前的文件有误。我已经上传了正确版本的测试结果。

Thank you so much

**Comment by haaWei** [comment]
> Sorry for the inconvenience, the previous files are wrong. I've uploaded the correct version of the test results.

Thank you so much
