### ISSUE TITLE
非常感谢作者工作，但有一处有点不清楚，期待回复

### ISSUE THREAD

**Issue by uacovz** [vision4robotics/SCT#4]
论文（6）公式中，^Xt-1 =  Xt-1 - N

但是SCT_model.py中，enchance中x=x+x-n
    def enhance(self, x,x_r):     
        x = x.contiguous()
        x_r, x_n = torch.split(x_r, 3, dim =1)
        x = x + x_n
        x = x + x_r*(torch.pow(x,2)-x)
        x = x + x_n
        x = x + x_r*(torch.pow(x,2)-x)
        x = x + x_n
        x = x + x_r*(torch.pow(x,2)-x)
        x = x + x_n
        x = x + x_r*(torch.pow(x,2)-x)	
        x = x + x_n	
        x = x + x_r*(torch.pow(x,2)-x)
        x = x + x_n	
        x = x + x_r*(torch.pow(x,2)-x)	
        x = x + x_n
        x = x + x_r*(torch.pow(x,2)-x)
        x = x + x_n
        enhance_image = x + x_r*(torch.pow(x,2)-x)

        return enhance_image

**Comment by Jay-Ye** [comment]
Hi there,
Thanks for your question. 
Actually, “+” or "-" don't matter here, since we are training a deep model. You can regard `x_n` as (-N), and then the code aligns with the equation. You may find this [blog](https://www.zhihu.com/question/433548556/answer/2938153423?utm_id=0) helpful.
